before_install:
- openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv
  -in service-account.json.enc -out service-account.json -d

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: service-account.json
  project: multi-k8s-312904